repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.0.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
      language_version: python3.6
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
      language_version: python3.6
    - id: end-of-file-fixer
      exclude: .bumpversion.cfg
    - id: flake8
      language_version: python3.6
      additional_dependencies: ["flake8-string-format", "flake8-per-file-ignores"]
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, develop, --branch, master]
-   repo: https://github.com/schmir/Ethlint.git
    rev: bbbac907e7352d59fcd133f73295a042a2cdcb17
    hooks:
    - id: solium
      args: [--dir=contracts]
- repo: git://github.com/luismayta/pre-commit-mypy
  sha: '0.1.1'
  hooks:
  - id: mypy
    args: ["--scripts-are-modules", "--ignore-missing-imports"]
