dist: trusty
sudo: false
language: python
python:
- "3.6"
git:
  depth: false
branches:
  only:
  - master
  - develop
  - /^[0-9]+/
stages:
  - name: testing
  - name: deploying

notifications:
  webhooks:
    urls:
      - secure: "47kfxfxOWTBPkAiDI0hsD7qA1aHRWAMJmHP7IdJLTwiRX2PhFOkjkaM98IiAZMHkPbvgXo8rSqfvzyBlztrWP78VHIZmL38ICt3sZ+VZ/WM+TKtq67jV4/ENPdkqPRPA6KCPQzQy93gtGM222ql9PCIYy8xz55fb9vqulYwis7H36zLXnwqywIXwJNa/w37UTmWSyzgHAeKOPfXosdoYU9N+0pQHnxJOI2JHQlwok2sJQZXWjRnp/ZLKl/chkdlW02mjnqwFeLBe+4laySYhFZ5WFcyrhV93bm4MLVLQp0lHAFT4u2hw2S2Kn8Bjv13wN/7wDhEwJ5IRGenM4JMfIxCdyeAwsA1g5crDrBPa0mrj0eTzA+X1mgmyWfd3seNpDb+COEzO5WT/+VGmMFp1boDN5SJgp4KDLiw2oJRefvdQufQmCmB01pbHcGwsFljIcP33VA4sk5/uhsz7RAV+Y1k/2vfO0Yv79HfO5yYIN04Xp5jZCla4QQ3WYmYWsE8O1V2IG1oyp6LRB1ssC2bJWOtHcUbpjMqXFQSL3wW2erKNwMEg8IaXBGUGxVHo1P79bvblrgGna+p64bAFb5tR57eCSmgB2cRiUzeU4M1C7xBnXT4zOwGNQ2M8M0PU9LzqtXD2TYRR0VdMPvmL7ikFzntQWXeGs9dFCMRiVI5QlCo="
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: testing
      name: tests
      install:
      - pip install -c constraints.txt -r requirements.txt
      - curl -L -o $HOME/bin/solc https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux && chmod +x $HOME/bin/solc
      - /usr/bin/env VIRTUALENV='virtualenv -p python3' make install-non-editable
      script:
      - flake8 py-bin py-deploy tests
      - pytest tests

    - stage: testing
      name: contractslinter
      install:
      - npm install -g 'solium@>=1.0.9'
      script:
      - solium --dir contracts/

    - stage: deploying
      name: docker
      sudo: true
      service: docker
      env:
        - DOCKER_USER=trustlinesautomation
        - secure: "OUd7EDE965JGrz/q09FM+lNmKCIfFF+wHAjt87+T3CLHLspY0vnXuONPLYDG95fZKPFy0IP1irHHvfjji3PGh278lfrcBxcILXaK+1qTfHIewHzu3/kv+ltyjQY4KRctO3wcD/5XUmpQO6ENrBPqh+6sn8VmhwbxyFJUEwX9wWvxc2H2fghaFtcH3apYpWgfCXsMGHwX/NWn1ifJvNVVhZUAsdjNyun9gz+SIqa+YdT17xstoE35DctbdBKsn5z2PLvGqE8LVC1CguAUGZO0RJR1WIlpNcxc8lkoZvezvi0b2q5xMfiJ62cA2l/WQFXVkqtY5l/qNwDn8Vnm+6H5warsD6paMu/6rgSfKzujte4GK3lXAs2AHBy5q81UV40XWCsZojC7OcKBNKglBGq/YysPs0O6xUKoT+FcHbdem+NPMTz3bbeOomGSaure5L3Lh30WzOzDK648m3eNdyt7lo/E0AbnJ8gDzCiAP4t1/GvCuv78ZxktD5TpA4TI3oIDHLqTNk6YtfcrtyKPfBjBKWlYiOY2AeqwOY3fYSp3A/BgYtqKWwr+zZpWnVv0jWz0vsqYrQzvAb3PLrX3yTWrK9fwrZlOi1t44qq+OF4PDog1Snd8/7KtW3rwMpPqWywinWJP3sUkJkTBEdW+fksVKzS1to51aOtZgJJ+Ehg43lk="
      install:
        - docker build -t parity-dev . -f .travis/Dockerfile-parity-dev
      script:
        - docker build -t contracts .
        - ./run-docker-smoketest
      deploy:
        skip_cleanup: true
        provider: script
        script: ".travis/push-docker-image.sh"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(develop|[0-9]+.*)$

    - stage: deploying
      name: pypi bin
      install:
      - pip install -c constraints.txt -r requirements.txt
      - curl -L -o $HOME/bin/solc https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux && chmod +x $HOME/bin/solc
      - /usr/bin/env VIRTUALENV='virtualenv -p python3' make compile
      script:
        - /bin/true
      before_deploy:
        - cd py-bin
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: trustlines
          password:
            secure: "x95gza22ssIhsMghLvViVN7Y1DJDDC0qNDb4Xqgj3lPjZ7p91ZoGBy8IQDdhGgDA9GQBlfij0kKU5FnUnQI3IBBtTEstOpH+QctwBvlLSKX3lx0gqx36ciQRE6nBr5onVjaxr+39pZ5hmX37eq069Pv1GxWJzBuSh2pcHudyO7tzSnSYjDkqurR/NE0A3XiLym1cOIrsmlYdLY2RUbBWIOuuVethauHiI+aF/9VUsywp5ZL2eo2mFIjuMCOWU5DMQuYdlMyNBYuQruufIQq47JuyJ5h65/JLup7lYZQw7A5/s7kkAHyxRbjyJTCbNZ/nJjLD5h+XL7YGnMT/tzQgXjV9DENKx21AgnYEpNzgdgqJLdcE2eFUYKKtIkI1WONtk8J2+XJyZa/gwjcw+y00yNsKALgfpqStUW2Ze/liI9AbruPYtjgyhwmqqvfTZrk4q/v21AtZygOh32iYeoEtrWNuhV8jHXe1M17MhtJFdso7AIJYJyY8PQeC8t5QU2yvOm577rRKx42UAECT2RoZS1HI8ECL872mS2yvSoURjuOfPWwAaYrA4kL8Snt3iMb/gvSVaUdA1XV4J83PTiNwqX953R2PCgFFSdKj/DRNnVEQh9AmMT4XV6wUJobXOGGa7yo1udecJPtUuLKO02W438sifnp9gsL5wCUgZAOTh6Y="
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$

    - stage: deploying
      name: pypi deploy
      install:
        - /bin/true
      script:
        - /bin/true
      before_deploy:
        - cd py-deploy
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: trustlines
          password:
            secure: "x95gza22ssIhsMghLvViVN7Y1DJDDC0qNDb4Xqgj3lPjZ7p91ZoGBy8IQDdhGgDA9GQBlfij0kKU5FnUnQI3IBBtTEstOpH+QctwBvlLSKX3lx0gqx36ciQRE6nBr5onVjaxr+39pZ5hmX37eq069Pv1GxWJzBuSh2pcHudyO7tzSnSYjDkqurR/NE0A3XiLym1cOIrsmlYdLY2RUbBWIOuuVethauHiI+aF/9VUsywp5ZL2eo2mFIjuMCOWU5DMQuYdlMyNBYuQruufIQq47JuyJ5h65/JLup7lYZQw7A5/s7kkAHyxRbjyJTCbNZ/nJjLD5h+XL7YGnMT/tzQgXjV9DENKx21AgnYEpNzgdgqJLdcE2eFUYKKtIkI1WONtk8J2+XJyZa/gwjcw+y00yNsKALgfpqStUW2Ze/liI9AbruPYtjgyhwmqqvfTZrk4q/v21AtZygOh32iYeoEtrWNuhV8jHXe1M17MhtJFdso7AIJYJyY8PQeC8t5QU2yvOm577rRKx42UAECT2RoZS1HI8ECL872mS2yvSoURjuOfPWwAaYrA4kL8Snt3iMb/gvSVaUdA1XV4J83PTiNwqX953R2PCgFFSdKj/DRNnVEQh9AmMT4XV6wUJobXOGGa7yo1udecJPtUuLKO02W438sifnp9gsL5wCUgZAOTh6Y="
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$

    - stage: deploying
      name: npm bin
      before_install:
        - sudo apt-get install -y nodejs npm
      install:
      - pip install -c constraints.txt -r requirements.txt
      - curl -L -o $HOME/bin/solc https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux && chmod +x $HOME/bin/solc
      - /usr/bin/env VIRTUALENV='virtualenv -p python3' make compile
      script:
        - /bin/true
      before_deploy:
        - cd py-bin
        - npm version $(git describe --tags)
      deploy:
        - provider: npm
          skip_cleanup: true
          email:
            secure: "WEgsJKf3ZVcFOaXje0xT//J8VVXZGKYLMZcfSJjIEWdpKuXtEC+tgOihGMXgzpnlpOBTUCgPWd1y1qGuDeGBMW71TdTKC8We5xUc+rfyk7aeuyNWb7WhYRaisNAxxtlS9AstWRGPlSlFeMD0UxFAZxqQU3Dd/6/Zpk7Rz2PP0K09UXldIGEXDMr20p0yqY5cO78i0sCGHq7Nv+uKtahb2cLJ9RNu12JUZbPPJaLT4mHRRbupx7VV0/xuiAO5lvvmWQDSOrjzGF1qjeLRQMc76ttPxdrU3LrWfRaxcF59uMBsZ7NDXFiNLM6xJ1GjJyFvgiuYUqZuqwGBNIwtMXE0PWsvaeikO1IAP7hw1KMtJg00hglFcdea4JBr3hXyRzh/V7OrtOeArO5o7GYyaQ9pOxjwhTOOkJF/3EFEH6U9uEXJhQVSq7EBNXRI3J1itcm4AOmMNzp27SW7yAyg6uKacjYn1ce5BNZ/imIZlC5b2ftib4yyok0AP4bfuNHoEQNwbhvZox51rM/vVraPg/eZwRvzY/5X2wrP8aHZ/mkl8zbzTiaqMN2D+zVPMyWHxhr1VvxUqpgVnBWmh1j+QQqP6hjV+rmi8/62nH/A4+XWf/GU4ThwnnbGeTqCPvHUsHW4L1WK2ka6xb602sxh8o0dzFJdsgkH0F/JSmjC0QF+Wj8="
          api_key:
            secure: "l9BHCuZQMY0MEA8Sg6xVwGzk+6LBoG1ep009/LYfrDedbqHRqURUCW8+a+mEnlhKtfgV1IBOHhvZRqCZszuq1jRSrMipEDzpfDLpbcOFkTfto+UUiQq8GF6oUG1uMoy+Ow4eZef1zAo0g9hfwVrrvUv8riOjeYZjYZ+pwva7PxIWCGX72kD40/WgHpYkPJLp1KO4ITqyy3VqaL1u5hDnAECOiKiXwSa06I5oVab6lCfceXFeNtNmivFCUag1wMsUJm5GQ4+E16X5hm40DzJGqupaL4sHo8sQwNHRIeBu1PbLO76UjmpbIFfV4mlt75NvUi6zGqFL+PRyEIvE71JDPiwXl9+9YL9ZBpfwJdjTJHa2TmyPdtE+VdoNYFnY34wrkNoMGB/cjcMuN7NlNJBhXmvMCJB48iIE+aaEM/t+oVxd7KNYpCKFE9izOnPMINAEMWvOq2o5JnTx3xGBqArENLpx1IevsoKXYYIchigPeI2tLmC5Hy8n9D/i8uFvQprjntVVLldEfA+GYIG0h0kg48qolUqTEknM174ce51l4HuyQV6c9HJoWQu5Z+Tbds6hYU3dSR5Cu7HM4BclrBQiL52sCkKTva6Dyr/WWQsLgbEpDQ1zCUGKV1nvzUWoAftbnkNw78ZMjHQzkW51PxlhxljK/QRTe6Cw9pSPHQo72EU="
          tag: latest
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$
