version: 2.1

templates:
  tagged-filter: &tagged-filter
    tags:
      only: /[0-9]+(\.[0-9]+)*/

executors:
  ubuntu-builder:
    docker:
      - image: trustlines/builder:master25
        environment:
          - SOLC_VERSION=v0.5.8
    working_directory: ~/repo
    environment:
      DOCKER_REPO: trustlines/contracts
      LOCAL_IMAGE: contracts

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  create-venv:
    description: "Create venv"
    steps:
      - run:
          name: Create python venv
          command: |
            python3 -m venv venv
            pip install -U pip wheel setuptools

  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo >> ${BASH_ENV} 'export PATH=~/bin:~/repo/venv/bin:${PATH}'
          echo >> ${BASH_ENV} '. ~/.nvm/nvm.sh'

  publish-npm:
    description: Publish npm package
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: Set authentication token
          command: |
            echo >> ~/.npmrc "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      - run:
          name: Set npm version
          command: |
            cd py-bin
            ./set_npm_version.sh
            cd ..
      - run:
          command: |
            cd py-bin
            npm publish --tag << parameters.tag >>

jobs:
  run-flake8:
    executor: ubuntu-builder

    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run flake8
          command: |
            flake8 py-bin py-deploy tests

  run-black:
    executor: ubuntu-builder

    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run black
          command: |
            black --check py-bin py-deploy tests
  run-solium:
    executor: ubuntu-builder

    steps:
      - checkout
      - config-path
      - run:
          name: Install ethlint (=solium)
          command: |
            npm install -g 'ethlint@1.2.5'
      - run:
          name: Run solium
          command: |
            solium --dir contracts
  install:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - create-venv

      - restore_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install requirements
          command: |
            make install-requirements
      - save_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
            - .requirements-installed
      - run:
          name: Install py-bin/py-deploy
          command: |
            make install
      - run:
          name: Build python distributions
          command: |
            make dist
      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  upload-pypi:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Upload to pypi
          command: |
            twine upload py-bin/dist/* py-deploy/dist/*

  upload-npm-dev:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - publish-npm:
          tag: "dev"

  upload-npm-latest:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - publish-npm:
          tag: "latest"


  run-pytest:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run pytest
          command: pytest

  run-mypy:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run mypy
          command: |
            mypy --ignore-missing-imports py-deploy/tldeploy tests

  build-docker-image:
    executor: ubuntu-builder

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build . -t $LOCAL_IMAGE
      - run:
          name: Save docker image
          command: |
            mkdir -p ~/images
            docker save --output ~/images/$LOCAL_IMAGE.tar $LOCAL_IMAGE
      - persist_to_workspace:
          root: "~"
          paths:
            - images

  run-smoketests:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - checkout
      - run:
          name: Load docker image
          command: |
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: Run smoketests
          command: |
            ./run-docker-smoketest

  deploy-docker-image:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - run:
          name: Load docker image
          command: |
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Upload tagged release
          command: |
            version=$(docker run --rm --entrypoint '' $LOCAL_IMAGE cat VERSION | tr '+' '_')
            echo "Tagging with $version"
            docker tag $LOCAL_IMAGE $DOCKER_REPO:$version
            docker push $DOCKER_REPO:$version
      - run:
          name: Upload latest
          command: |
            docker tag $LOCAL_IMAGE $DOCKER_REPO:latest
            docker push $DOCKER_REPO:latest

  run-end2end-tests:
    executor: ubuntu-builder
    working_directory: ~
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - run:
          name: Checkout end2end repo
          command: |
            git clone https://github.com/trustlines-protocol/end2end.git
      - run:
          name: Load docker image
          command: |
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: run end2end tests
          command: |
            docker tag $LOCAL_IMAGE $DOCKER_REPO
            cd end2end
            ./run-e2e.sh

workflows:
  version: 2
  default:
    jobs:
      - run-solium:
          filters:
            <<: *tagged-filter

      - run-flake8:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - run-black:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - run-mypy:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - install:
          filters:
            <<: *tagged-filter

      - run-pytest:
          filters:
            <<: *tagged-filter
          requires:
            - install

      - upload-npm-dev: &upload-npm
          context: npm-credentials
          filters:
            branches:
              only:
                - master

          requires:
            - run-solium
            - run-flake8
            - run-black
            - run-mypy
            - install
            - run-pytest
            - run-smoketests

      - upload-npm-latest:
          <<: *upload-npm
          filters:
            <<: *tagged-filter
            branches:
              ignore: /.*/

      - upload-pypi:
          context: pypi-credentials
          filters:
            <<: *tagged-filter
            branches:
              ignore: /.*/
          requires:
            - run-solium
            - run-flake8
            - run-black
            - run-mypy
            - run-pytest
            - install
            - run-smoketests

      - build-docker-image:
          filters:
            <<: *tagged-filter

      - run-smoketests:
          filters:
            <<: *tagged-filter
          requires:
            - build-docker-image

      - deploy-docker-image:
          context: docker-credentials
          filters:
            <<: *tagged-filter
            branches:
              only: master
          requires:
            - run-solium
            - run-flake8
            - run-black
            - run-pytest
            - run-mypy
            - install
            - build-docker-image
            - run-smoketests

      - run-end2end-tests:
          filters:
            <<: *tagged-filter
          requires:
            - build-docker-image
